### ISSUE TITLE
Request for domain: pulse.alpha.canada.ca 

### ISSUE THREAD

**Issue by tparrott-cse** [cds-snc/dns#104]
Request for gcpulse.tbs.alpha.canada.ca to be allocated for TBS' tracker2.0 testing purposes

**Comment by obrien-j** [comment]
You want to shoot me an appropriate TF zone file in here (take a look at digital.canada.ca) and I can push a PR for you.

Alternatively, if you want delegation for *.cyber.alpha.canada.ca, I'm open to that as well.

**Comment by ptd-tbs** [comment]
Can this be gcpulse.alpha.canada.ca instead? Is department name required for these testing domains?

**Comment by obrien-j** [comment]
pulse.alpha.canada.ca it is!
