### ISSUE TITLE
URL requests for healthcare portal 

### ISSUE THREAD

**Issue by sidewalkballet** [cds-snc/dns#123]
Two requests for a home for https://github.com/cds-snc/covid-healthcare-portal 

* `covid-alert-portal.alpha.canada.ca`
* `portail-alerte-covid.alpha.canada.ca`

**Comment by obrien-j** [comment]
Sounds good...

Just need the relevant place to point them to. @bryan-robitaille Mind taking a shot at a PR? Take a look at the one below as a reference, they're pretty straight forward.

https://github.com/cds-snc/dns/pull/122

**Comment by bryan-robitaille** [comment]
Working with Max to get the domains white listed so that I can get an SSL cert through AWS Certificate Manager.  Once I can get the DNS CName verifcation entries I'll submit the PR with the CNames to the hosting servers as well as the required validation.

**Comment by bryan-robitaille** [comment]
PR submitted #124

**Comment by bryan-robitaille** [comment]
Merged and up and running.
Thanks everyone!
