### ISSUE TITLE
Forensic DMARC reports directed to Cyber Centre

### ISSUE THREAD

**Issue by michaeldavie-cyber** [cds-snc/dns#157]
I came across a CDS DMARC record that is directing forensic reports to the Cyber Centre, but couldn't find the record in this repo: https://emailstuff.org/dmarc/check/qe0e6xs.m.notification.alpha.canada.ca

Please amend this record to remove the `ruf=mailto:dmarc@cyber.gc.ca` portion.

**Comment by maxneuvians** [comment]
Hi @michaeldavie-cyber, I have changed the records for all `m.notification.alpha.canada.ca` subdomains. It looks like the record no longer shows up. Thank you for letting us know.
