### ISSUE TITLE
Subdomain request for cra-arc.alpha.canada.ca

### ISSUE THREAD

**Issue by delisma** [cds-snc/dns#178]
```
resource "aws_route53_record" "cra-arc-alpha-canada-ca-NS" {
  zone_id = aws_route53_zone.alpha-canada-ca-public.zone_id
  name    = "cra-arc.alpha.canada.ca"
  type    = "NS"
  records = [
    "ns1-06.azure-dns.com",
    "ns2-06.azure-dns.net",
    "ns3-06.azure-dns.org",
    "ns4-06.azure-dns.info"
  ]
  ttl = "300"
}
```
In order for Microsoft to authorize use of the cra-arc.alpha.canada.ca domain name with Azure Active Directory for Canada Revenue Agency - Agence du revenue Canada, we need to add a DNS entry for it.
    
    In order to verify cra-arc.alpha.canada.ca, we need to add the following TXT record for cra-arc.alpha.canada.ca with the domain registrar or in Azure DNS records:
    
    Alias or host name: @
    Destination or points to address: MS=ms25509347
    TTL: 3600
    
    If your domain registrar for cra-arc.alpha.canada.ca does not allow TXT records, as an alternative you can add the following MX record:
    
    Alias or host name: @
    Destination or points to address: ms25509347.msv1.invalid
    TTL: 3600
    Priority: 32767
    
    Please let me know once the DNS entry has been added. From there I can unblock our use of cra-arc.alpha.canada.ca with Azure AD by completing the verification process for the domain name.
    
    Thank you.
cc/ @HamzaAburaneh, @obrien-j

**Comment by obrien-j** [comment]
Looks good. Before we put this in, can I just get a confirmtion that CRA's cool with this. :)

**Comment by delisma** [comment]
@obrien-j How do you want CRA to confirm it to you? We have a MOU from them asking us to setup a Azure environment (tenancy) on our platform. Will that do?
cc/ @pcwsmith

**Comment by obrien-j** [comment]
Sounds good @delisma . Good enough for me. Just for records, this is for a CRA dns record/zone within the TBS Azure tenant oui?

**Comment by delisma** [comment]
> Sounds good @delisma . Good enough for me. Just for records, this is for a CRA dns record/zone within the TBS Azure tenant oui?

Indeed

**Comment by AntoineAugusti** [comment]
@delisma Done 👌 

```
$ dig cra-arc.alpha.canada.ca in ns

; <<>> DiG 9.10.6 <<>> cra-arc.alpha.canada.ca in ns
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50226
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;cra-arc.alpha.canada.ca.	IN	NS

;; ANSWER SECTION:
cra-arc.alpha.canada.ca. 300	IN	NS	ns1-06.azure-dns.com.
cra-arc.alpha.canada.ca. 300	IN	NS	ns2-06.azure-dns.net.
cra-arc.alpha.canada.ca. 300	IN	NS	ns3-06.azure-dns.org.
cra-arc.alpha.canada.ca. 300	IN	NS	ns4-06.azure-dns.info.

;; Query time: 108 msec
;; SERVER: 192.168.0.25#53(192.168.0.25)
;; WHEN: Fri Mar 05 13:07:28 EST 2021
;; MSG SIZE  rcvd: 281
```
